q()
d = data.frame(al=c(5,3), a2=c('a','b')
d = data.frame(al=c(5,3), a2=c('a','b')
d = data.frame(al=c(5,3), a2=c('a','b')
d = data.frame(al=c(5,3), a2=c('a','b'))
print(d)
print(d)
d = data.frame(al=c(5,3), a2=c('a','b'))
d = data.frame(al=c(5,3), a2=c('a','b'
d = data.frame(al=ca2=c('a','b'
d = data.frame(al=c(5,3), a2=c('a','b'))
d = data.frame(man=c(5,3), women=c('a','b'))
print(d)
ucicar <- read.table("car.data.csv, sep=',', header=T)
ucicar <- read.table("car.data.csv', sep=',', header=T)
print(ucicar)
print(ucicar)
getwd()
pdrmDirectory <- read.csv(file="C:/Users/HYee/Documents/direktori-pdrm.csv",header=TRUE,sep=",")
pdrmDirectory <- read.csv(file="C:/Users/HYee/Documents/direktori-pdrm(1).csv",header=TRUE,sep=",")
pdrmDirectory <- read.csv(file="C:/Users/HYee/Documents/direktori-pdrm.csv",header=TRUE,sep=",")
print(pdrmDirectoty)
print(pdrmDirectory)
pdrmDirectory <- read.csv(file="C:/Users/HYee/Documents/direktori-pdrm.csv",header=TRUE,sep=",")
Install.packages("RCurl")
install.packages("RCurl")
Install.packages("Rcurl")
Install.packages("RCurl")
urlBase <- 'https://raw.githubusercontent.com/WinVector/PDSwR2/master/'
Install.packages("Rcurl")
Install.packages("RCurl")
install.packages("RCurl")
library(RCurl)
urlBase <- 'https://raw.githubusercontent.com/WinVector/PDSwR2/master/'
mkCon <- function(nm) { textConnection(getURL(paste(urlBase,nm,sep='')))}
cars <- read.table(mkCon('UCICar/car.data.csv'), sep=',', header=T)
txCon <- textConnection('geturl('https://raw.githubusercontent.com/WinVector/PDSwR2/master/UCICar/car.data.csv'))
txCon <- textConnection('getURL('https://raw.githubusercontent.com/WinVector/PDSwR2/master/UCICar/car.data.csv'))
txCon <- textConnection(getURL('https://raw.githubusercontent.com/WinVector/PDSwR2/master/UCICar/car.data.csv'))
txCon
cars1<-read.table(txCon,sep=',',header=T)
install.packages("class")
save.image("C:\\Users\\HYee\\Desktop\\.RData")
url <-"http://www.data.gov.my/data/dataset/b5cd948f-cffb-4439-ae08-e508ff073a93/resource/1f2d5629-ac8d-449a-a4c1-9d269d625d84/download/lokalitihotspot2015.xlsx"
download.file(url, "dengue.xlsx", mode='wb')
dt <- read.csv(file="dengue.csv",header=TRUE, sep=",")
dt <- read.csv(file="dengue.csv", header=TRUE, sep=",")
dt <- read.csv(file="dengue.csv", header=TRUE, sep=",")
names(dt)
names(dt) <-gsub(".",'', names(dt), fixed=TRUE)
names(dt) <- c("Year", "week", "state", "District","Location", "Total", "Outbreak Duration")
names(dt)[2] <- 'week No'
names(dt) ,- gsub(" ", "_", names(dt))
names(dt) <- gsub(" ", "_", names(dt))
save.image("C:\\Users\\HYee\\Desktop\\dengue")
install.packages("RMySQL")
library(RMySQL)
con <- dbConnect(RMySQL::MySQL(), dbname = "tweater", host = "courses.csrrinzqubik.us-east-1.rds.amazonaws.com", port = 3306, user = "student", password = "datacamp")
tables = dbListTables(con)
tables = dbListTables(con)
tables = dbListTables(con)
con
con <- dbConnect(RMySQL::MySQL(), dbname = "tweater", host = "courses.csrrinzqubik.us-east-1.rds.amazonaws.com", port = 3306, user = "student", password = "datacamp")
install.packages("RMySQL")
library(RMySQL)
con <- dbConnect(RMySQL::MySQL(), dbname = "tweater", host = "courses.csrrinzqubik.us-east-1.rds.amazonaws.com", port = 3306, user = "student", password = "datacamp")
tables = dbListTables(con)
str(tables)
users <- dbReadTable(con, "users")
print(users)
users <- dbReadTable(con, "comments")
users <- dbReadTable(con, "comments")
con <- dbConnect(RMySQL::MySQL(), dbname = "tweater", host = "courses.csrrinzqubik.us-east-1.rds.amazonaws.com", port = 3306, user = "student", password = "datacamp")
tables = dbListTables(con)
str(tables)
users <- dbReadTable(con, "users")
users <- dbReadTable(con, "comments")
users <- dbReadTable(con, "users")
print(users)
> comments <- dbReadTable(con, "comments")
> print(comments)
> tweats <- dbReadTable(con, "tweats")
> print(tweats)
comments <- dbReadTable(con, "comments")
print(comments)
tweats <- dbReadTable(con, "tweats")
print(tweats)
con <- dbConnect(RMySQL::MySQL(), dbname = "tweater", host = "courses.csrrinzqubik.us-east-1.rds.amazonaws.com", port = 3306, user = "student", password = "datacamp")
comments <- dbReadTable(con, "comments")
print(comments)
tweats <- dbReadTable(con, "tweats")
print(tweats)
q()
q()
q()
View(cars1)
getwd()
summary(custData)
1/4
34324832482394/234234
x-7>5, x=?
load("C:/Users/HYee/Desktop/New folder/.RData")
summary()
> setwd("C:/Users/HYee/Desktop/New folder")
setwd("C:/Users/HYee/Desktop/New folder")
getwd()
Covid19 <- read.table('MN997409.1-4NY0T82X016-Alignment-HitTable.csv', sep=',', header=T)
summary(Covid19)
